# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_design_asset'),
        ('mukluk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designasset',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='shop.Product'),
            preserve_default=False,
        ),
    ]
