# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mukluk', '0002_designasset_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designasset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_asset', to='shop.Product'),
        ),
    ]
