# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mukluk', '0004_designedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='site',
        ),
        migrations.AlterModelOptions(
            name='designedproduct',
            options={'verbose_name': 'Designed Product', 'verbose_name_plural': 'Designed Products'},
        ),
        migrations.RemoveField(
            model_name='designasset',
            name='product',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='design_asset',
        ),
        migrations.AddField(
            model_name='designasset',
            name='designed_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='design_assets', to='mukluk.DesignedProduct'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InventoryProduct',
        ),
    ]
