# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 18:53
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mukluk', '0005_auto_20180831_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='designedproduct',
            name='sku',
            field=cartridge.shop.fields.SKUField(blank=True, max_length=20, null=True, verbose_name='SKU'),
        ),
    ]
