# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mukluk', '0006_designedproduct_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignedProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('file', mezzanine.core.fields.FileField(max_length=255, verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('designed_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mukluk.DesignedProduct')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('_order',),
            },
        ),
    ]
