# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0004_auto_20180831_1753'),
        ('mukluk', '0007_designedproductimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_string', models.CharField(blank=True, editable=False, max_length=500)),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL')),
                ('_meta_title', models.CharField(blank=True, help_text='Optional title to be used in the HTML title tag. If left blank, the main title field will be used.', max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('gen_description', models.BooleanField(default=True, help_text='If checked, the description will be automatically generated from content. Uncheck if you want to manually set a custom description.', verbose_name='Generate description')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text="With Published chosen, won't be shown until this time", null=True, verbose_name='Published from')),
                ('expiry_date', models.DateTimeField(blank=True, help_text="With Published chosen, won't be shown after this time", null=True, verbose_name='Expires on')),
                ('short_url', models.URLField(blank=True, null=True)),
                ('in_sitemap', models.BooleanField(default=True, verbose_name='Show in sitemap')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
            },
        ),
        migrations.AlterModelOptions(
            name='designedproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='designasset',
            name='designed_product',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='content',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='content_model',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='site',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='status',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='title',
        ),
        migrations.RemoveField(
            model_name='designedproduct',
            name='vendor_shop',
        ),
        migrations.RemoveField(
            model_name='designedproductimage',
            name='description',
        ),
        migrations.AlterField(
            model_name='designedproduct',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='design',
            name='possible_products',
            field=models.ManyToManyField(related_name='designs', through='mukluk.DesignedProduct', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='design',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='design',
            name='vendor_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='mukluk.VendorShop'),
        ),
        migrations.AddField(
            model_name='designasset',
            name='design',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='design_assets', to='mukluk.Design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designedproduct',
            name='design',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mukluk.Design'),
            preserve_default=False,
        ),
    ]
