# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 20:20
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mukluk', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mukluk.DesignAsset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mukluk.InventoryProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='markup',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Markup'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mukluk.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_shop',
            field=models.ManyToManyField(to='mukluk.VendorShop'),
        ),
    ]
