# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180821_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='design_asset',
        ),
    ]
