# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mukluk', '0004_designedproduct'),
        ('shop', '0003_remove_product_design_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='markup',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_shop',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mukluk.Brand'),
            preserve_default=False,
        ),
    ]
