# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mukluk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershop',
            options={'verbose_name': 'User Shop', 'verbose_name_plural': 'User Shops'},
        ),
    ]
